src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Repository\PostsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostsRepository::class)
 */
class Posts
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $post_title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $post_slug;

    /**
     * @ORM\Column(type="text")
     */
    private $post_content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $post_image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $post_created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $post_updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="posts")
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Categories::class, inversedBy="posts")
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="post")
     */
    private $comments;

    public function __construct()
    {
        $this->categorie = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPostTitle(): ?string
    {
        return $this->post_title;
    }

    public function setPostTitle(string $post_title): self
    {
        $this->post_title = $post_title;

        return $this;
    }

    public function getPostSlug(): ?string
    {
        return $this->post_slug;
    }

    public function setPostSlug(string $post_slug): self
    {
        $this->post_slug = $post_slug;

        return $this;
    }

    public function getPostContent(): ?string
    {
        return $this->post_content;
    }

    public function setPostContent(string $post_content): self
    {
        $this->post_content = $post_content;

        return $this;
    }

    public function getPostImage(): ?string
    {
        return $this->post_image;
    }

    public function setPostImage(string $post_image): self
    {
        $this->post_image = $post_image;

        return $this;
    }

    public function getPostCreatedAt(): ?\DateTimeInterface
    {
        return $this->post_created_at;
    }

    public function setPostCreatedAt(\DateTimeInterface $post_created_at): self
    {
        $this->post_created_at = $post_created_at;

        return $this;
    }

    public function getPostUpdatedAt(): ?\DateTimeInterface
    {
        return $this->post_updated_at;
    }

    public function setPostUpdatedAt(?\DateTimeInterface $post_updated_at): self
    {
        $this->post_updated_at = $post_updated_at;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Categories[]
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(Categories $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
        }

        return $this;
    }

    public function removeCategorie(Categories $categorie): self
    {
        $this->categorie->removeElement($categorie);

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }
}

src/Form/PostsType.php
<?php

namespace App\Form;

use App\Entity\Posts;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('post_title')
            ->add('post_slug')
            ->add('post_content')
            ->add('post_image')
            ->add('post_created_at')
            ->add('post_updated_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Posts::class,
        ]);
    }
}

src/Controller/PostsController.php
<?php

namespace App\Controller;

use App\Entity\Posts;
use App\Form\PostsType;
use App\Repository\PostsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/posts")
 */
class PostsController extends AbstractController
{
    /**
     * @Route("/", name="posts_index", methods={"GET"})
     */
    public function index(PostsRepository $postsRepository): Response
    {
        return $this->render('posts/index.html.twig', [
            'posts' => $postsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="posts_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $post = new Posts();
        $form = $this->createForm(PostsType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($post);
            $entityManager->flush();

            return $this->redirectToRoute('posts_index');
        }

        return $this->render('posts/new.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="posts_show", methods={"GET"})
     */
    public function show(Posts $post): Response
    {
        return $this->render('posts/show.html.twig', [
            'post' => $post,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="posts_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Posts $post): Response
    {
        $form = $this->createForm(PostsType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('posts_index');
        }

        return $this->render('posts/edit.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="posts_delete", methods={"POST"})
     */
    public function delete(Request $request, Posts $post): Response
    {
        if ($this->isCsrfTokenValid('delete' . $post->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($post);
            $entityManager->flush();
        }

        return $this->redirectToRoute('posts_index');
    }
}

templates/posts/_delete_form.html.twig
<form method="post" action="{{ path('posts_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn">Delete</button>
</form>

templates/posts/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/posts/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Posts{% endblock %}

{% block body %}
    <h1>Edit Posts</h1>

    {{ include('posts/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('posts_index') }}">back to list</a>

    {{ include('posts/_delete_form.html.twig') }}
{% endblock %}

templates/posts/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Posts index{% endblock %}

{% block body %}
    <h1>Posts index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Post_title</th>
                <th>Post_slug</th>
                <th>Post_content</th>
                <th>Post_image</th>
                <th>Post_created_at</th>
                <th>Post_updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr>
                <td>{{ post.id }}</td>
                <td>{{ post.postTitle }}</td>
                <td>{{ post.postSlug }}</td>
                <td>{{ post.postContent }}</td>
                <td>{{ post.postImage }}</td>
                <td>{{ post.postCreatedAt ? post.postCreatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ post.postUpdatedAt ? post.postUpdatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('posts_show', {'id': post.id}) }}">show</a>
                    <a href="{{ path('posts_edit', {'id': post.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('posts_new') }}">Create new</a>
{% endblock %}

templates/posts/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Posts{% endblock %}

{% block body %}
    <h1>Create new Posts</h1>

    {{ include('posts/_form.html.twig') }}

    <a href="{{ path('posts_index') }}">back to list</a>
{% endblock %}

templates/posts/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Posts{% endblock %}

{% block body %}
    <h1>Posts</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ post.id }}</td>
            </tr>
            <tr>
                <th>Post_title</th>
                <td>{{ post.postTitle }}</td>
            </tr>
            <tr>
                <th>Post_slug</th>
                <td>{{ post.postSlug }}</td>
            </tr>
            <tr>
                <th>Post_content</th>
                <td>{{ post.postContent }}</td>
            </tr>
            <tr>
                <th>Post_image</th>
                <td>{{ post.postImage }}</td>
            </tr>
            <tr>
                <th>Post_created_at</th>
                <td>{{ post.postCreatedAt ? post.postCreatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Post_updated_at</th>
                <td>{{ post.postUpdatedAt ? post.postUpdatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('posts_index') }}">back to list</a>

    <a href="{{ path('posts_edit', {'id': post.id}) }}">edit</a>

    {{ include('posts/_delete_form.html.twig') }}
{% endblock %}